---
- name: Get VM names from vSphere
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Gather virtual machines in folder
      community.vmware.vmware_vm_info:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        folder: "{{ folder }}"
      delegate_to: localhost
      register: vm_info

    - name: Print VM names
      debug:
        msg: "{{ item.guest_name }}"
      loop: "{{ vm_info.virtual_machines }}"