---
- name: Get VM names from vSphere
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware
  pre_tasks:
     - include_vars: locked.yml
  vars_files:
      - vars.yml
  tasks:
    - name: Gather virtual machines in folder
      community.vmware.vmware_vm_info:
        hostname: "{{ VMWARE_HOSTNAME }}"
        username: "{{ VMWARE_USERNAME }}"
        password: "{{ VMWARE_PASSWORD }}"
        validate_certs: no
        folder: "{{ VCENTER_DESTINATION_FOLDER }}"
      delegate_to: localhost
      register: vm_info

    - name: Print VM names
      debug:
        msg: "{{ item.guest_name }}"
      loop: "{{ vm_info.virtual_machines }}"